/*
    @author kenneth.cruz@unah.hn
    @version 0.1.0
    @date 2021/05/22
*/


INSERT INTO Country(tex_name, tex_iso) VALUES 
    ('Andorra','AD'),
    ('United Arab Emirates','AE'),
    ('Afghanistan','AF'),
    ('Antigua and Barbuda','AG'),
    ('Anguilla','AI'),
    ('Albania','AL'),
    ('Armenia','AM'),
    ('Netherlands Antilles','AN'),
    ('Angola','AO'),
    ('Antarctica','AQ'),
    ('Argentina','AR'),
    ('American Samoa','AS'),
    ('Austria','AU'),
    ('Australia','AS'),
    ('Aruba','AW'),
    ('Azerbaijan','AZ'),
    ('Bosnia and Herzegovina','BA'),
    ('Barbados','BB'),
    ('Bangladesh','BD'),
    ('Belgium','BE'),
    ('Burkina Faso','BF'),
    ('Bahrain','BH'),
    ('Burundi','BI'),
    ('Benin','BJ'),
    ('Bermuda','BM'),
    ('Bolivia','BO'),
    ('Brazil','BR'),
    ('Bahamas','BS'),
    ('Bhutan','BT'),
    ('Bouvet Island','BU'),
    ('Bulgaria','BV'),
    ('Botswana','BW'),
    ('Brunei Darussalam','BX'),
    ('Belarus','BY'),
    ('Belize','BZ'),
    ('Canada','CA'),
    ('Cocos (Keeling) Islands','CC'),
    ('Central African Republic','CF'),
    ('Congo','CG'),
    ('Switzerland','CH'),
    ("Cote D'Ivoire (Ivory Coast)",'CI'),
    ('Cook Islands','CK'),
    ('Chile','CL'),
    ('Cameroon','CM'),
    ('China','CN'),
    ('Colombia','CO'),
    ('Costa Rica','CR'),
    ('Cuba','CU'),
    ('Cape Verde','CV'),
    ('Christmas Island','CX'),
    ('Cyprus','CY'),
    ('Czech Republic','CZ'),
    ('Germany','DE'),
    ('Djibouti','DJ'),
    ('Denmark','DK'),
    ('Dominica','DM'),
    ('Dominican Republic','DO'),
    ('Algeria','DZ'),
    ('Ecuador','EC'),
    ('Estonia','EE'),
    ('Egypt','EG'),
    ('Western Sahara','EH'),
    ('Eritrea','ER'),
    ('Spain','ES'),
    ('Ethiopia','ET'),
    ('Finland','FI'),
    ('Fiji','FJ'),
    ('Falkland Islands (Malvinas)','FK'),
    ('Micronesia','FM'),
    ('Faroe Islands','FO'),
    ('France','FR'),
    ('Gabon','GA'),
    ('Great Britain (UK)','GB'),
    ('Grenada','GD'),
    ('Georgia','GE'),
    ('French Guiana','GF'),
    ('Ghana','GH'),
    ('Gibraltar','GI'),
    ('Greenland','GL'),
    ('Gambia','GM'),
    ('Guinea','GN'),
    ('Guadeloupe','GP'),
    ('Equatorial Guinea','GQ'),
    ('Greece','GR'),
    ('South Georgia and South, Sandwich Islands','GS'),
    ('Guatemala','GT'),
    ('Guam','GU'),
    ('Guinea-Bissau','GW'),
    ('Guyana','GY'),
    ('Hong Kong','HK'),
    ('Heard and McDonald Islands','HM'),
    ('Honduras','HN'),
    ('Croatia and Hrvatska','HR'),
    ('Haiti','HT'),
    ('Hungary','HU'),
    ('Indonesia','ID'),
    ('Ireland','IE'),
    ('Israel','IL'),
    ('India','IN'),
    ('British Indian Ocean Territory','IO'),
    ('Iraq','IQ'),
    ('Iran','IR'),
    ('Iceland','IS'),
    ('Italy','IT'),
    ('Jamaica','JM'),
    ('Jordan','JO'),
    ('Japan','JP'),
    ('Kenya','KE'),
    ('Kyrgyzstan','KG'),
    ('Cambodia','KH'),
    ('Kiribati','KI'),
    ('Comoros','KM'),
    ('Saint Kitts and Nevis)','KN'),
    ('Korea North','KP'),
    ('Korea South','KR'),
    ('Kuwait','KW'),
    ('Cayman Islands','KY'),
    ('Kazakhstan','KZ'),
    ('Laos','LA'),
    ('Lebanon','LB'),
    ('Saint Lucia','LC'),
    ('Liechtenstein','LI'),
    ('Sri Lanka','LK'),
    ('Liberia','LR'),
    ('Lesotho','LS'),
    ('Lithuania','LT'),
    ('Luxembourg','LU'),
    ('Latvia','LV'),
    ('Libya','LY'),
    ('Morocco','MA'),
    ('Monaco','MC'),
    ('Moldova','MD'),
    ('Madagascar','MG'),
    ('Marshall Islands','MH'),
    ('Macedonia','MK'),
    ('Mali','ML'),
    ('Myanmar','MM'),
    ('Mongolia','MN'),
    ('Macau','MO'),
    ('Northern Mariana Islands','MP'),
    ('Martinique','MQ'),
    ('Mauritania','MR'),
    ('Montserrat','MS'),
    ('Malta','MT'),
    ('Mauritius','MU'),
    ('Maldives','MV'),
    ('Malawi','MW'),
    ('Mexico','MX'),
    ('Malaysia','MY'),
    ('Mozambique','MZ'),
    ('Namibia','NA'),
    ('New Caledonia','NC'),
    ('Niger','NE'),
    ('Norfolk Island','NF'),
    ('Nigeria','NG'),
    ('Nicaragua','NI'),
    ('Netherlands','NE'),
    ('Norway','NO'),
    ('Nepal','NP'),
    ('Nauru','NR'),
    ('Niue','NU'),
    ('New Zealand','NZ'),
    ('Oman','OM'),
    ('Panama','PA'),
    ('Peru','PE'),
    ('French Polynesia','PF'),
    ('Papua New Guinea','PG'),
    ('Philippines','PH'),
    ('Pakistan','PK'),
    ('Poland','PO'),
    ('St. Pierre and Miquelon','PM'),
    ('Pitcairn','PN'),
    ('Puerto Rico','PR'),
    ('Portugal','PT'),
    ('Palau','PW'),
    ('Paraguay','PY'),
    ('Qatar','QA'),
    ('Reunion','RE'),
    ('Romania','RO'),
    ('Russian Federation','RU'),
    ('Rwanda','RW'),
    ('Saudi Arabia','SA'),
    ('Solomon Islands','SB'),
    ('Seychelles','SC'),
    ('Sudan','SD'),
    ('Sweden','SE'),
    ('Singapore','SG'),
    ('St. Helena','SH'),
    ('Slovenia','SI'),
    ('Svalbard and Jan Mayen, Islands','SJ'),
    ('Slovak Republic','SK'),
    ('Sierra Leone','SL'),
    ('San Marino','SM'),
    ('Senegal','SN'),
    ('Somalia','SO'),
    ('Suriname','SR'),
    ('Sao Tome and Principe','ST'),
    ('El Salvador','SV'),
    ('Syria','SY'),
    ('Swaziland','SZ'),
    ('Turks and Caicos Islands','TC'),
    ('Chad','TD'),
    ('French Southern Territories', 'TF'),
    ('Togo','TG'),
    ('Thailand','TH'),
    ('Tajikistan','TI'),
    ('Tokelau','TK'),
    ('Turkmenistan','TM'),
    ('Tunisia','TN'),
    ('Tonga','TO'),
    ('East Timor','TP'),
    ('Turkey','TR'),
    ('Trinidad and Tobago','TT'),
    ('Tuvalu','TV'),
    ('Taiwan','TW'),
    ('Tanzania','TZ'),
    ('Ukraine','UA'),
    ('Uganda','UG'),
    ('United Kingdom','UK'),
    ('US Minor Outlying Islands','UM'),
    ('United States of America (USA)','US'),
    ('Uruguay','UY'),
    ('Uzbekistan','UZ'),
    ('Vatican City State', 'VA'),
    ('Saint Vincent and the, Grenadines','VC'),
    ('Venezuela','VE'),
    ('Virgin Islands (British)','VG'),
    ('Viet Nam','VN'),
    ('Vanuatu','VU'),
    ('Wallis and Futuna Islands','WF'),
    ('Samoa','WS'),
    ('Yemen','YE'),
    ('Mayotte','YT'),
    ('Yugoslavia','YU'),
    ('South Africa','ZA'),
    ('Zambia','ZM'),
    ('Zaire','ZR'),
    ('Zimbabwe','ZW')
;



-- Clientes
INSERT INTO User(id_country_fk, tex_firstname, tex_secondname, tex_firstsurname, tex_secondsurname, tex_accessCode) VALUES
 (1, 'Saraann', 'Eula', 'Jull', 'Clewer', 'cli-0001-6zD'),
 (3, 'Joannes', 'Jarvis', 'Ryson', 'Varty', 'cli-0002-0F4'),
 (4, 'Ave', 'Fredia', 'Impson', 'Aicheson', 'cli-0003-1yF'),
 (5, 'Salli', 'Elmore', 'Panchin', 'Nisen', 'cli-0004-RTE'),
 (5, 'Clari', 'Poul', 'Gotling', 'Gouldie', 'cli-0005-2Dh'),
 (5, 'Shelby', 'Latisha', 'Broadberrie', 'Adnett', 'cli-0006-WEo'),
 (6, 'Eduino', 'Corissa', 'Hearne', 'Dosdill,', 'cli-0007-qD2')
;


-- Empleados
INSERT INTO User(id_country_fk, tex_firstname, tex_secondname, tex_firstsurname, tex_secondsurname, bit_type, tex_accessCode) VALUES
 (2, 'Guntar', 'Rubina', 'Kemm', 'Barnewille', 1, 'emp-0008-pyh'),
 (2, 'Deane', 'Kingsley', 'Aish', 'Idenden', 1, 'emp-0009-EOo'),
 (2, 'Beulah', 'Gordy', 'Knagges', 'Mockford',1, 'emp-0010-6lU')
;


INSERT INTO Phonenumber(id_user_fk, tex_prefix, tex_number) VALUES
 (1, '+86', '802 494 1154'),
 (2, '+353', '335 860 5888'),
 (3, '+66', '446 693 8856'),
 (4, '+62', '872 478 5170'),
 (5, '+86', '822 761 6944'),
 (6, '+56', '588 742 7276'),
 (7, '+380', '467 549 1968'),
 (8, '+504', '517 171 0578'),
 (9, '+504', '893 696 8442'),
 (10, '+504', '155 324 4780')
;


INSERT INTO Client(id_user_fk, tex_passport) VALUES
 (1, 'mQsELhIcT7w2'),
 (2, 'uj1D1sK4JFOE'),
 (3, 'ssqSKiyaelZU'),
 (4, 'gIt6FEgJfWBZ'),
 (5, 'f6DcJZdClPG0'),
 (6, 'WZAP0jmXocWA'),
 (7, 'ZjnZrq4v5I5C')
;


-- identicador empleado
INSERT INTO Employee(id_user_fk, dob_salary, tim_hiringDate) VALUES
 (8, 16840.19, '2023-02-27 00:00:00'),
 (9, 10526.36, '2021-05-02 00:00:00'),
 (10, 8434.64, '2020-01-14 00:00:00')
;